version: "2"

services:
  ingester:
    build:
      context: ./ingester
      dockerfile: Dockerfile
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    command: /go/bin/service-ingester
    environment:
      - RMQ_HOST=rabbitmq

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    command: /go/bin/service-worker
    environment:
      - RMQ_HOST=rabbitmq

  rabbitmq:
    image: rabbitmq:alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"

  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
